// Questions
var q = [
	'What is it that you do?',
	'How did you come up with this idea?',
	'Why did you choose this idea?',
	'Why is now the right time for this product to exist? (Rather than 10 years ago or 10 years from now)',
	'How big an opportunity is there?',
	'How do you make money?',
	'What does your average client pay?',
	'Who uses your product?',
	'How do you know people want this?',
	'What do you understand about your users?',
	'What has surprised you about user behaviour?',
	'How do you grow?',
	'How will you get users?',
	'How are you meeting customers?',
	'How will customers and/or users find out about you?',
	'Where do new users come from?',
	'Why do clients seek your product?',
	'What resistance will they have to trying you and how will you overcome it?',
	'Why do the reluctant users hold back?',
	'What do you know about this space/product others dont know?',
	'What do you understand that others dont?',
	'What, exactly, makes you different from existing options?',
	'Whats new about what you make?',
	'Why will you succeed?',
	'Who are your competitors?',
	'Who might become competitors?',
	'What competition do you fear most?',
	'Why isnt someone already doing this?',
	'How are you going to prevent people from copying you?',
	'Where is the rocket science here?',
	'How does your product work in more detail?',
	'So what are you working on?',
	'What is the next step with the product evolution?',
	'Have you raised funding?',
	'How long can you go before funding?',
	'What is your burn rate?',
	'What is your growth/traction like?',
	'What is your user growth rate?',
	'What domain expertise do you have?',
	'How did your team meet?',
	'How do we know your team will stick together?',
	'Who in your team does what?',
	'Why did your team get together?',
	'Six months from now, whats going to be your biggest problem?',
	'What obstacles will you face and how will you overcome them?',
	'What problems/hurdles are you anticipating?',
	'How much money could you make per year?',
	'If your startup succeeds, what additional areas might you be able to expand into?',
	'What are you going to do next?',
	'Who would you hire or how would you add to your team?',
	'Are you open to changing your idea?',
	'Someone just showed us an idea like this right before you guys. I dont like it. What else do you have?',
	'What will you do if we dont fund you?',
	'How far will you be by the end of Y Combinator?',
	'Why YC',
	'Why you?',
	'Will you reincorporate as a US company?',
	'Would you relocate to Silicon Valley?',
	'In what ways are you resourceful?',
	'Tell us about a tough problem you solved?',
	'Tell us something surprising you have done?',
	'What have you learned so far from working on your product?',
	'Whats the biggest mistake you have made?',
	'Whats the funniest thing that has happened to you?',
	'Whats the worst thing that has happened?',
	'Errors and what you learned from them',
	'Whatts an impressive thing you have done?',
	'So do you sell freight?',
	'Why do you not sell freight?',
	'When will you go international?',
	'Why didnt ML buy you?',
	'Who uses your product on a daily basis?',
	'Who will buy you in 5 years?',
	'What will you do if Amazon enters the market?',
	'What wil you do it Cainiao(AliBaba enters the market?',
	'Why do you have so little equity?',
	'How much equity do you have?',
	'Will your investors accept 7% of YC?',
	'Why would your investors accept YC dilution?',
	'What is the worst part of your business?',
	'How big is the opportunity outside of Brazil?',
	'Why did you prioritize break-even?',
	'How much money will you raise now?',
	'Why ARPA varies so much?',
	'Why is e-commerce still 80% of your business?',
	'Would you have a business in the US?',
	'What is your growth like?',
	'What else have you created together?',
	'What is the next step with the product evolution?',
	'What do you know about this space/product others don&#39;t know?'
];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];
